function ff=f(xx,yy,k,tt)

global alpha lambda mu

%       ff(xx,yy,t) = {f1,f2}'
    
if k==1     % Primera componente del vector ff (f1)          
    ff= exp(tt)*(12*mu*(-1 + xx)^3*(-1 + yy)^2 - 12*mu*xx^3*yy^2 + ...
        mu*xx*yy*cos(xx*yy)*sin(xx) - 2*mu*(-1 + xx)*cos((-1 + xx)*(-1 + yy))*sin(1 - yy) + ...
        mu*cos(1 - yy)*sin((-1 + xx)*(-1 + yy)) + mu*(-1 + xx)^2*cos(1 - yy)*sin((-1 + xx)*(-1 + yy)) - ...
        2*mu*(2 + 6*xx*yy^4 - (-1 + yy)^2*cos(1 - yy)*sin((-1 + xx)*(-1 + yy))) + mu*xx*cos(xx)*sin(xx*yy) +...
        mu*sin(xx)*sin(xx*yy) - lambda*(2 - 12*(-1 + xx)^3*(-1 + yy)^2 + 6*xx*yy^4 - xx*yy*cos(xx*yy)*sin(xx) - ...
        (-1 + yy)^2*cos(1 - yy)*sin((-1 + xx)*(-1 + yy)) - xx*cos(xx)*sin(xx*yy) - sin(xx)*sin(xx*yy)));
else        % Segunda componente del vector ff (f2)   
    ff= exp(tt)*(-2*mu*(2 - 6*(-1 + xx)^4*(-1 + yy) - xx^2*cos(xx*yy)*sin(xx)) - ...
        lambda*(2 - 6*(-1 + xx)^4*(-1 + yy) + 12*xx^2*yy^3 + cos(1 - yy)*cos((-1 + xx)*(-1 + yy)) - ...
        xx^2*cos(xx*yy)*sin(xx) + (-1 + yy)*cos((-1 + xx)*(-1 + yy))*sin(1 - yy) - ...
        (-1 + xx)*(-1 + yy)*cos(1 - yy)*sin((-1 + xx)*(-1 + yy))) - ...
        mu*(-12*(-1 + xx)^2*(-1 + yy)^3 + 12*xx^2*yy^3 + cos(1 - yy)*cos((-1 + xx)*(-1 + yy)) - ...
        cos(xx*yy)*sin(xx) - yy^2*cos(xx*yy)*sin(xx) + (-1 + yy)*cos((-1 + xx)*(-1 + yy))*sin(1 - yy) - ...
        (-1 + xx)*(-1 + yy)*cos(1 - yy)*sin((-1 + xx)*(-1 + yy)) - 2*yy*cos(xx)*sin(xx*yy)));
end
       
return
end