function sol=sol_exactax_sigma(xx,yy,tt,nu,row,col)

% global alpha

%       sigma(xx,yy,tt) = [sigma(1,1) sigma(1,2);sigma(2,1) sigma(2,2)]

 if row==1 && col==1       % Solución analítica de sigma (1,1) (xx,yy,tt)
     sol=(exp(tt)*(5 + sin(5*pi*xx)*sin(5*pi*yy))*(xx*(2 + 3*xx*yy^4) + (-1 + yy)*cos(1 - yy)*cos((-1 + xx)*(-1 + yy)) +...
         (nu*(2*(-1 + yy) - 3*(-1 + xx)^4*(-1 + yy)^2 + xx*(2 + 3*xx*yy^4) +  ...
         (-1 + yy)*cos(1 - yy)*cos((-1 + xx)*(-1 + yy)) - xx*sin(xx)*sin(xx*yy)))/(1 - 2*nu)))/(1 + nu);     
 elseif row==1 && col==2   % Solución analítica de sigma (1,2) (xx,yy,tt)
     sol=(exp(tt)*(5 + sin(5*pi*xx)*sin(5*pi*yy))*(-4*(-1 + xx)^3*(-1 + yy)^3 + 4*xx^3*yy^3 +...
         (-1 + xx)*cos(1 - yy)*cos((-1 + xx)*(-1 + yy)) + cos(xx)*cos(xx*yy) + sin(1 - yy)*sin((-1 + xx)*(-1 + yy)) - ...
         yy*sin(xx)*sin(xx*yy)))/(2.*(1 + nu));
 elseif row==2 && col==1   % Solución analítica de sigma (2,1) (xx,yy,tt)
     sol=(exp(tt)*(5 + sin(5*pi*xx)*sin(5*pi*yy))*(-4*(-1 + xx)^3*(-1 + yy)^3 + 4*xx^3*yy^3 + ...
         (-1 + xx)*cos(1 - yy)*cos((-1 + xx)*(-1 + yy)) + cos(xx)*cos(xx*yy) + sin(1 - yy)*sin((-1 + xx)*(-1 + yy)) -...
         yy*sin(xx)*sin(xx*yy)))/(2.*(1 + nu));
 else                       % Solución analítica de sigma (2,2) (xx,yy,tt)
     sol=(exp(tt)*(5 + sin(5*pi*xx)*sin(5*pi*yy))*(2*(-1 + yy) - 3*(-1 + xx)^4*(-1 + yy)^2 - xx*sin(xx)*sin(xx*yy) + ...
         (nu*(2*(-1 + yy) - 3*(-1 + xx)^4*(-1 + yy)^2 + xx*(2 + 3*xx*yy^4) +  ...
         (-1 + yy)*cos(1 - yy)*cos((-1 + xx)*(-1 + yy)) - xx*sin(xx)*sin(xx*yy)))/(1 - 2*nu)))/(1 + nu);
 end

return
end